# Autogenerated by devscripts/update-version.py

__version__ = '2023.03.05.114514'

RELEASE_GIT_HEAD = '2c9cbd992650038d6c04bdeb53400b53be471987'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
