# Autogenerated by devscripts/update-version.py

__version__ = '2023.03.04.140134'

RELEASE_GIT_HEAD = 'a2cb339ee56bbdf6c78e4720003998552462956f'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
